### ISSUE TITLE
Settings App crashed

### ISSUE THREAD

**Issue by Waxaranai** [Komodo-OS/packages_apps_Settings#10]
Process: com.android.settings
PID: 17230
UID: 1000
Flags: 0x38c9be45
Package: com.android.settings v30 (11)
Foreground: Yes
Process-Runtime: 1378951
Build: google/redfin/redfin:11/RQ3A.210705.001/7380771:user/release-keys

java.lang.RuntimeException: Unable to resume activity {com.android.settings/com.android.settings.SubSettings}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.ListPreference.setEntries(java.lang.CharSequence[])' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4438)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:58)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5414)
	at android.app.ActivityThread.access$3300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2076)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.ListPreference.setEntries(java.lang.CharSequence[])' on a null object reference
	at com.android.settings.development.OverlayCategoryPreferenceController.updateState(OverlayCategoryPreferenceController.java:175)
	at com.android.settings.dashboard.DashboardFragment.updatePreferenceStates(DashboardFragment.java:390)
	at com.android.settings.dashboard.DashboardFragment.onResume(DashboardFragment.java:221)
	at androidx.fragment.app.Fragment.performResume(Fragment.java:2973)
	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:594)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1339)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1477)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1555)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1608)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3046)
	at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3004)
	at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:273)
	at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:405)
	at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:394)
	at android.app.Activity.performResume(Activity.java:8154)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4428)
	... 14 more

**Comment by Kry9toN** [comment]
Is fixed now i will close this issue

Thanks you for your contribution
